export interface StaticReview {
  id: string
  author: string
  initials: string
  rating: number
  text: string
  date: string
}

export const STATIC_REVIEWS: StaticReview[] = [
  {
    id: '1',
    author: 'Angelica Pham',
    initials: 'AP',
    rating: 5,
    text: 'I was able to easily make a same day appointment for ink fingerprints (F-258) by phone call. The service was quick and easy, and it took about 25 minutes total. I had a fantastic experience and would recommend TruIdentity Screening Solutions to anyone who needs fingerprints done.',
    date: '2 months ago',
  },
  {
    id: '2',
    author: 'David Cummings',
    initials: 'DC',
    rating: 5,
    text: "Bill is great! He's professional, punctual, and clearly knows his stuff. I'd recommend using TruIdentity Screening Solutions for sure.",
    date: '3 weeks ago',
  },
  {
    id: '3',
    author: 'ray perez',
    initials: 'RP',
    rating: 5,
    text: 'Bill was fast, courteous, and professional. Definitely recommend!',
    date: '2 months ago',
  },
  {
    id: '4',
    author: 'roland lee james',
    initials: 'RJ',
    rating: 5,
    text: 'What a pleasant experience. Very informative, very helpful, very thorough and got the prints done in a timely manner. Thanks !!',
    date: '4 months ago',
  },
  {
    id: '5',
    author: 'Lesley Parra',
    initials: 'LP',
    rating: 5,
    text: 'Bill is great to work with friendly. Best quality print job in town.',
    date: '3 months ago',
  },
  {
    id: '6',
    author: 'David Villarreal',
    initials: 'DV',
    rating: 5,
    text: 'Easy to set up appointment online. Mr. Hawkins was very professional and explained the process very well. Highly recommended.',
    date: '7 months ago',
  },
  {
    id: '7',
    author: 'Santana Rodriguez',
    initials: 'SR',
    rating: 5,
    text: 'Great service, fast, professional, very reasonable price, highly recommended if you need fingerprints.',
    date: '7 months ago',
  },
  {
    id: '8',
    author: 'Alexzander Santos (Zander)',
    initials: 'AS',
    rating: 5,
    text: "I had a great experience getting my fingerprints processed for a new job. Mr. Hawkins was incredibly polite, professional, and made the whole process smooth and stress-free. He was right on time for my appointment and took care of everything quickly and efficiently. It's always nice to support a local small business, especially one that clearly takes pride in excellent customer service. Highly recommend!",
    date: 'a year ago',
  },
  {
    id: '9',
    author: 'Maria Figueroa',
    initials: 'MF',
    rating: 5,
    text: "Amazing service! I was able to get an ink fingerprint appointment the same day I called. The best part is they can come to you! I had my fingerprints taken right from home. Bill Hawkins lll was very professional and kind. Don't hesitate to book!",
    date: 'a year ago',
  },
  {
    id: '10',
    author: 'Vale Rodriguez Q.',
    initials: 'VR',
    rating: 5,
    text: 'Great experience! Super fast and easy.',
    date: '3 months ago',
  },
  {
    id: '11',
    author: 'Israel Coronado',
    initials: 'IC',
    rating: 5,
    text: 'Excellent Service! Just called … made an appointment and done ✅',
    date: 'a year ago',
  },
  {
    id: '12',
    author: 'alma garza',
    initials: 'AG',
    rating: 5,
    text: 'He visited my residence promptly, providing an excellent service. The police department was unable to accommodate me due to the holidays, and no other fingerprinting services offered ink fingerprinting. However, he was able to assist me, which was essential for my nursing license. He conducted the fingerprinting in a highly professional and courteous manner.',
    date: 'a year ago',
  },
  {
    id: '13',
    author: 'Emma Cavazos',
    initials: 'EC',
    rating: 5,
    text: 'Needed to get fingerprints done for grad school and I received excellent service here.',
    date: '5 months ago',
  },
  {
    id: '14',
    author: 'Wiki Woof',
    initials: 'WW',
    rating: 5,
    text: "I purchased the ink fingerprinting services from Bill Hawkins. He arrived on time and was very professional and courteous. I had some initial misgivings because there is only a mobile service option, meaning he will come to your home, but I shouldn't have worried because everything went well. I did see on the website that you could also choose a different location than your home address for the actual fingerprinting as well. Price was good as other options were more expensive and it was very convenient because he comes right to you.",
    date: 'a year ago',
  },
  {
    id: '15',
    author: 'Issrael García',
    initials: 'IG',
    rating: 5,
    text: 'Good service, fast and very kind',
    date: '4 months ago',
  },
  {
    id: '16',
    author: 'Angela Chapa',
    initials: 'AC',
    rating: 5,
    text: 'Great service! It was fast and he explained and guided me through the process. He was patient and also accommodating I definitely recommend.',
    date: 'a year ago',
  },
  {
    id: '17',
    author: 'yahaira de leon',
    initials: 'YD',
    rating: 5,
    text: 'Bill was great! I needed my fingerprints done for employment purposes. The fingerprint process went smoothly with Mr. Hawkins and I would definitely recommend him for anyone needed fingerprints done.',
    date: 'a year ago',
  },
  {
    id: '18',
    author: 'Mary Alice Rodriguez',
    initials: 'MR',
    rating: 5,
    text: 'Mr. Hawkins was very professional and the mobility service he offers he came to my office / home was extremely convenient for a busy person such as myself. It also saved me gas and time. Will definitely recommend Mr. Hawkins.',
    date: '2 years ago',
  },
  {
    id: '19',
    author: 'Megan Sanchez',
    initials: 'MS',
    rating: 5,
    text: 'Very easy and quick. Had no trouble what so ever. Would recommend going for fast finger prints',
    date: '10 months ago',
  },
  {
    id: '20',
    author: 'Joanne Flores',
    initials: 'JF',
    rating: 5,
    text: 'I called multiple unreliable companies before finally finding TruIdentity Screening Solutions. I have used them twice. He is reliable, organized and professional. I would not go with anyone else. Thank you!',
    date: 'a year ago',
  },
  {
    id: '21',
    author: 'C',
    initials: 'C',
    rating: 5,
    text: "TruIdentity's mobile service is quick and easy. The owner was professional, courteous, and knowledgeable, making the entire experience seamless. I highly recommend TruIdentity Screening Solutions for their excellent service! Se habla español.",
    date: '2 years ago',
  },
  {
    id: '22',
    author: 'Henry',
    initials: 'H',
    rating: 5,
    text: 'Excellent service nice guy could not recommend any more highly for identification verification services',
    date: '8 months ago',
  },
  {
    id: '23',
    author: 'A White',
    initials: 'AW',
    rating: 5,
    text: 'Very professional, respectful, on time, great communication and was quick! The mobile service was an option I needed. Thanks so much!',
    date: 'a year ago',
  },
  {
    id: '24',
    author: 'erika hernandez',
    initials: 'EH',
    rating: 5,
    text: "I highly recommend Bill Hawkins he is professional he knows what he's doing and he only does mobile printing at the moment meaning that he comes to your house or where ever you'd like to meet him! So the address on Google is not his office.",
    date: 'a year ago',
  },
  {
    id: '25',
    author: 'Roxann Espinoza',
    initials: 'RE',
    rating: 5,
    text: 'Tru Identity Screening Solutions scheduled me ASAP and I was able to get my appointment done at an early time. Thank you Mr. Hawkins!',
    date: 'a year ago',
  },
  {
    id: '26',
    author: 'Teena Bobby',
    initials: 'TB',
    rating: 5,
    text: 'Great experience. Thank you!',
    date: '4 months ago',
  },
  {
    id: '27',
    author: 'Zachary Perez',
    initials: 'ZP',
    rating: 5,
    text: 'Easy registration and quick appointment!!',
    date: 'a month ago',
  },
  {
    id: '28',
    author: 'brandon edwards',
    initials: 'BE',
    rating: 5,
    text: 'I needed a company that could provide my ATF electronic fingerprint file and I was able to find Tru Identity. Bill was very informative and made my fingerprinting experience very easy. I will be recommending to all my friends.',
    date: '2 years ago',
  },
  {
    id: '29',
    author: 'Jessica Lerma',
    initials: 'JL',
    rating: 5,
    text: "His services were very professional and timely. I'm glad he was patient with my fingerprints 😊 thank you so much!",
    date: 'a year ago',
  },
  {
    id: '30',
    author: 'Joel Hernandez',
    initials: 'JH',
    rating: 5,
    text: 'Gentleman on time, I hundred percent recommend this business he explains every step. The process was simple and quick thank you.',
    date: 'a year ago',
  },
  {
    id: '31',
    author: 'leslie 11d',
    initials: 'LE',
    rating: 5,
    text: 'Fast, friendly service. If you need something fast done like fingerprints. They are mobile so they come to you thanks!',
    date: 'a year ago',
  },
  {
    id: '32',
    author: 'Tiffany Rush',
    initials: 'TR',
    rating: 5,
    text: 'Service was fast and easy!',
    date: '3 months ago',
  },
  {
    id: '33',
    author: 'C B',
    initials: 'CB',
    rating: 5,
    text: 'Very reliable and punctual. Excellent customer service. Flexible with appointment scheduling.',
    date: 'a year ago',
  },
  {
    id: '34',
    author: 'Prakriti Arya',
    initials: 'PA',
    rating: 5,
    text: 'Very friendly and helpful',
    date: '5 months ago',
  },
  {
    id: '35',
    author: 'Anikka Garza',
    initials: 'AG',
    rating: 5,
    text: 'Great and convenient company! Fast and easy to get fingerprints done! Highly recommend',
    date: '2 years ago',
  },
  {
    id: '36',
    author: 'Gabriela Jaramillo',
    initials: 'GJ',
    rating: 5,
    text: 'Very fast and informational',
    date: '4 months ago',
  },
  {
    id: '37',
    author: 'Roel Vela',
    initials: 'RV',
    rating: 5,
    text: 'VERY PROFESSIONAL AND QUICK.',
    date: '5 months ago',
  },
  {
    id: '38',
    author: 'Gabriel Gonzales',
    initials: 'GG',
    rating: 5,
    text: 'easy and quick',
    date: '4 months ago',
  },
  {
    id: '39',
    author: 'celeste robles',
    initials: 'CR',
    rating: 5,
    text: 'Great service! Quick and accessible',
    date: 'a year ago',
  },
  {
    id: '40',
    author: 'Chris Anzaldua',
    initials: 'CA',
    rating: 5,
    text: 'Very quick, in and out',
    date: '6 months ago',
  },
  {
    id: '41',
    author: 'Destiny Martinez',
    initials: 'DM',
    rating: 5,
    text: 'Quick and simple! Easy way to get fingerprinting done.',
    date: 'a year ago',
  },
  {
    id: '42',
    author: 'Allison Smith',
    initials: 'AS',
    rating: 5,
    text: 'Easy and quick place to get fingerprints!',
    date: 'a year ago',
  },
  {
    id: '43',
    author: 'Betty Flores',
    initials: 'BF',
    rating: 5,
    text: 'Proficient. Professional and pleasant',
    date: 'a year ago',
  },
  {
    id: '44',
    author: 'Lesli Alva-Escobedo',
    initials: 'LA',
    rating: 5,
    text: 'Really good service.',
    date: 'a year ago',
  },
  {
    id: '45',
    author: 'Evelyn B',
    initials: 'EB',
    rating: 5,
    text: 'Fingerprinting done quickly!',
    date: '6 months ago',
  },
  {
    id: '46',
    author: 'Dr. Mary Alvarez',
    initials: 'MA',
    rating: 5,
    text: 'Punctual, courteous, and professional.',
    date: 'a year ago',
  },
  {
    id: '47',
    author: 'Sarah Love',
    initials: 'SL',
    rating: 5,
    text: 'Excellent service 👍',
    date: 'a year ago',
  },
  {
    id: '48',
    author: 'Breanna Gonzalez',
    initials: 'BG',
    rating: 5,
    text: 'Great experience getting my fingerprints rolled with Bill! He is very patient and thorough. Highly recommend him!',
    date: '3 days ago',
  },
  {
    id: '49',
    author: 'Armando Montemayor',
    initials: 'AM',
    rating: 5,
    text: 'Fast, kind, and professional!',
    date: '3 weeks ago',
  },
  {
    id: '50',
    author: 'Nicole S',
    initials: 'NS',
    rating: 5,
    text: 'Great service!!!!',
    date: 'a month ago',
  },
  {
    id: '51',
    author: 'Denise Rodriguez',
    initials: 'DR',
    rating: 5,
    text: 'Quick and easy!',
    date: '2 months ago',
  },
]
